name: "Mandy's Tasty Creations"
favicon: null
layout_spectrum: 0.63184
typography_spectrum: 0.30079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 0.8037261334247887
purpose: []
