name: "Mandy's Tasty Creations"
favicon: null
layout_spectrum: 0.6377191697247326
typography_spectrum: 0.15192494681105018
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.23002305394038558
  lightness: 0.13988842372782528
  saturation: 0.05134843522682786
  rhythmicContrast: 0.8037261334247887
purpose: []
